# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
      #Symfony documentation, read users from database
        our_db_provider:
            entity:
              class: AppBundle:User
              property: username

        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$5NMAwmNa8aebygeWdRWRlufW23M2.Ibzgr6X7C0OUaDk0fDuk/7iC
                        roles: 'ROLE_USER'
                    matt:
                        password: $2y$12$MS4PoFxfJIdv/KkuwI/2RuBSVdop1PJlsso4HGHUrS7icCaboS6G6
                        roles: 'ROLE_ADMIN'
                    admin:
                        password: $2y$12$iG57pC9Lxt8yKPrh9koSyOVGYjLlidTNVI01f.xsESdy5o4fHcsmO
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
        #    pattern:    ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: [ROLE_ADMIN] }

        #acess control multiple roles
        - { path: ^/user, roles: [ROLE_ADMIN, ROLE_USER] }


        #acess control multiple roles
        - { path: ^/collection, roles: [ROLE_ADMIN, ROLE_USER] }

        #acess control multiple roles
        - { path: ^/recipe/*/id, roles: [ROLE_ADMIN, ROLE_USER] }

    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: bcrypt
          cost: 12